# Generated by Django 3.2.7 on 2021-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('bills', 'Bills'), ('taxes', 'Taxes'), ('food', 'Food'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('misc', 'Miscellaenous')], max_length=64),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('bills', 'Bills'), ('taxes', 'Taxes'), ('food', 'Food'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('misc', 'Miscellaenous')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
