# Generated by Django 3.2.7 on 2021-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeplanner', '0002_auto_20211003_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='amount',
            new_name='max_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='isMaxed',
        ),
        migrations.RemoveField(
            model_name='week',
            name='date',
        ),
        migrations.AddField(
            model_name='goal',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
