# Generated by Django 3.2.7 on 2021-10-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeplanner', '0003_auto_20211003_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
