# Generated by Django 3.2.7 on 2021-10-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeplanner', '0004_auto_20211003_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='week',
        ),
        migrations.AddField(
            model_name='purchase',
            name='goal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pokeplanner.goal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Bills', 'Bills'), ('Taxes', 'Taxes'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Miscellaenous', 'Miscellaenous')], max_length=64),
        ),
    ]
