# Generated by Django 3.2.7 on 2021-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeplanner', '0005_auto_20211003_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
